# Generated by Django 5.0.4 on 2024-05-08 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0009_usercourse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercourse',
            old_name='Course',
            new_name='course',
        ),
    ]
